### ISSUE TITLE
Unable to install plugins with ionic framework app

### ISSUE THREAD

**Issue by DipakMahapurkar** [Telerik-Verified-Plugins/Facebook#12]
Hello, 
I am new one in ionic framework app development i want to integrate facebook in my app.
i am following give steps i get this problem when i install the given plugins, my console is:

cordova -d plugin add /Users/Desktop/Ionic 2 Demo/phonegap-facebook-plugin --save --variable APP_ID="app_id" --variable APP_NAME="App_Name"
Executing "before_plugin_add"  hook for all plugins.
No version specified, retrieving version from config.xml
No version given in config.xml, attempting to use plugin engine info
Error: Registry returned 404 for GET on https://registry.npmjs.org/ideasapp
    at makeError (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
    at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
    at Request._callback (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:963:12)

Please help me for this problem 
Thank You !!

**Comment by lakfa** [comment]
Hello @inceptiveDipak I am gettig the same issue here. Any update ?

**Comment by EddyVerbruggen** [comment]
@lakfa how are you installing the plugin and what's the result?

**Comment by lakfa** [comment]
Thanks for your reply @EddyVerbruggen 
I tried with >>
cordova -d plugin add \pathToLocalRepo\phonegap-facebook-plugin-master --variable APP_ID="APP_ID" --variable APP_NAME="APP_Name" and it gave the same error above
Then I tried >>
cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4 --save --variable APP_ID="APP_ID" --variable APP_NAME="APP_Name" and it works

**Comment by EddyVerbruggen** [comment]
Yeah not sure why you'd want a local clone anyway. Oh and that fork is not the same as this one so if you have any trouble please hop on over to their repo.

**Comment by lakfa** [comment]
@EddyVerbruggen sorry I ve just noticed that!!

**Comment by EddyVerbruggen** [comment]
No worries. Btw, this is the official doc for the verified plugin: http://plugins.telerik.com/cordova/plugin/facebook

**Comment by lakfa** [comment]
Hey @EddyVerbruggen Ive just integreted your plugin in my ios ionic app and it works just like a charm !!
